/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package software.project;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class Payment_Gateway extends javax.swing.JFrame {

    /**
     * Creates new form Payment_Gateway
     */
    
    
    
    DBconnection dbCon;
    ResultSet rs;
    ResultSet cs;
       
    private int price;
    private String Useremail;
    private String m_id ;    
    private int duration;
    public Payment_Gateway(int price, String Useremail, String m_id, int duration) {
        initComponents();
        this.setLocationRelativeTo(null);
        dbCon = new DBconnection();
        this.price = price;
        Price_field.setText(String.valueOf(price));
        this.Useremail = Useremail;
        this.m_id = m_id;
        this.duration = duration;
    }

    private Payment_Gateway(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditinfo_lbl = new javax.swing.JLabel();
        creditinfo_lbl2 = new javax.swing.JLabel();
        creditnum_field = new javax.swing.JTextField();
        mmyy_field = new javax.swing.JTextField();
        cvv_field = new javax.swing.JTextField();
        pay_btn = new javax.swing.JButton();
        Price_field = new javax.swing.JLabel();
        creditinfo_lbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        creditinfo_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        creditinfo_lbl.setText("Please enter your credit/debit card information below:");

        creditinfo_lbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        creditinfo_lbl2.setText("Credit/Debit number:");

        mmyy_field.setText("MM/YY");

        cvv_field.setText("CVV");

        pay_btn.setText("Pay");
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });

        Price_field.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Price_field.setText("-");

        creditinfo_lbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        creditinfo_lbl3.setText("Price :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creditinfo_lbl3)
                        .addGap(18, 18, 18)
                        .addComponent(Price_field)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditinfo_lbl2)
                            .addComponent(pay_btn)
                            .addComponent(creditinfo_lbl)
                            .addComponent(creditnum_field, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mmyy_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cvv_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(creditinfo_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditinfo_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price_field))
                .addGap(9, 9, 9)
                .addComponent(creditinfo_lbl2)
                .addGap(18, 18, 18)
                .addComponent(creditnum_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmyy_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvv_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(pay_btn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed
        // TODO add your handling code here:
       
        //"SELECT CARD_NUMBER , EXPIRY_DATE , SECURITY_CODE , BALANCE from CREDIT_CARD WHERE CARD_NUMBER = '5386128845631211' AND EXPIRY_DATE = '06/29' AND SECURITY_CODE = '223'"
        // Get selected machine ID and type
        String creditnum = creditnum_field.getText();
        String mmyy =  mmyy_field.getText();
        String ccv = cvv_field.getText();
       

        // Prepare SQL statement
        String query = "SELECT CARD_NUMBER , EXPIRY_DATE , SECURITY_CODE , BALANCE from CREDIT_CARD WHERE CARD_NUMBER = '" + creditnum + "' AND EXPIRY_DATE = '" + mmyy + "' AND SECURITY_CODE = '" + ccv + "'";
        
        
        try {
            rs = dbCon.executeStatement(query);

            if (rs.next()) {
                int balance = rs.getInt("BALANCE");
                
                if (balance >= price) {
                    int newBalance = balance - price;

                    String updateQuery = "UPDATE CREDIT_CARD SET BALANCE = ? WHERE CARD_NUMBER = ? AND EXPIRY_DATE = ? AND SECURITY_CODE = ?";
                    PreparedStatement prepStatement = dbCon.connection.prepareStatement(updateQuery);
                    prepStatement.setInt(1, newBalance);
                    prepStatement.setString(2, creditnum);
                    prepStatement.setString(3, mmyy);
                    prepStatement.setString(4, ccv);

                    int result = prepStatement.executeUpdate();

                    if (result > 0) {
                        JOptionPane.showMessageDialog(this, "Payment Successful");
                    } else {
                        JOptionPane.showMessageDialog(this, "Payment unsuccessful. Please try again later.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Insufficient Balance");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Card");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while processing your payment. Please try again later.");
        } 

        DBconnection d = new DBconnection();
        d.updateMachineStatus(m_id, duration);
  
    }//GEN-LAST:event_pay_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment_Gateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment_Gateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment_Gateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment_Gateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment_Gateway(0).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price_field;
    private javax.swing.JLabel creditinfo_lbl;
    private javax.swing.JLabel creditinfo_lbl2;
    private javax.swing.JLabel creditinfo_lbl3;
    private javax.swing.JTextField creditnum_field;
    private javax.swing.JTextField cvv_field;
    private javax.swing.JTextField mmyy_field;
    private javax.swing.JButton pay_btn;
    // End of variables declaration//GEN-END:variables
}
