/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package software.project;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class User_Interface extends javax.swing.JFrame {

   
    
    /**
     * Creates new form User_Interface
     */
    public User_Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        welcome_lbl = new javax.swing.JLabel();
        laund_pic = new javax.swing.JPanel();
        aboutus_lbl = new javax.swing.JLabel();
        contactus_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutus_text = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactus_text = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        machine_id_lbl = new javax.swing.JLabel();
        consumption_lbl = new javax.swing.JLabel();
        loc_lbl = new javax.swing.JLabel();
        consumption_field = new javax.swing.JLabel();
        loc_field = new javax.swing.JLabel();
        status_lbl = new javax.swing.JLabel();
        status_field = new javax.swing.JLabel();
        locked_lbl = new javax.swing.JLabel();
        locked_field = new javax.swing.JLabel();
        machineType_lbl = new javax.swing.JLabel();
        machineinfo_lbl = new javax.swing.JLabel();
        machineID_combobox = new javax.swing.JComboBox<>();
        machineType_combobox = new javax.swing.JComboBox<>();
        search_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        feedback_lbl = new javax.swing.JLabel();
        feedback_field = new javax.swing.JTextField();
        submit_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bookmach_lbl = new javax.swing.JLabel();
        machineid_combobox = new javax.swing.JComboBox<>();
        machine_lbl = new javax.swing.JLabel();
        avalibility_lbl = new javax.swing.JLabel();
        aval_lbl = new javax.swing.JLabel();
        bookmach_btn = new javax.swing.JButton();
        timeslot_lbl = new javax.swing.JLabel();
        timeslot_combobox = new javax.swing.JComboBox<>();
        price_lbl = new javax.swing.JLabel();
        price_field = new javax.swing.JLabel();
        machine_lbl1 = new javax.swing.JLabel();
        machinetype_combobox = new javax.swing.JComboBox<>();
        avalibility_lbl1 = new javax.swing.JLabel();
        period_combobox = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        offers_lbl = new javax.swing.JLabel();
        coupon_lbl = new javax.swing.JLabel();
        insta_lbl = new javax.swing.JLabel();
        coup_hash = new javax.swing.JLabel();
        thirdbook_lbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        myacc_lbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        username_lbl = new javax.swing.JLabel();
        usertype_lbl = new javax.swing.JLabel();
        phnum_lbl = new javax.swing.JLabel();
        balance_lbl = new javax.swing.JLabel();
        points_lbl1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        myAcc_menuBar = new javax.swing.JMenu();
        view_acc_menuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        logout_menuItem = new javax.swing.JMenuItem();
        services_menuBar = new javax.swing.JMenu();
        homepage_menuItem = new javax.swing.JMenuItem();
        faq_menuitem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        place_orderMenuItem = new javax.swing.JMenuItem();
        mach_info_menuItem = new javax.swing.JMenuItem();
        prov_feedback_menuItem = new javax.swing.JMenuItem();
        viewOffers_menuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_lbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        welcome_lbl.setText("Welcome to the Automated Laundry System");

        javax.swing.GroupLayout laund_picLayout = new javax.swing.GroupLayout(laund_pic);
        laund_pic.setLayout(laund_picLayout);
        laund_picLayout.setHorizontalGroup(
            laund_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
        );
        laund_picLayout.setVerticalGroup(
            laund_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        aboutus_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutus_lbl.setText("About Us:");

        contactus_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactus_lbl.setText("Contact Us:");

        aboutus_text.setEditable(false);
        aboutus_text.setColumns(20);
        aboutus_text.setRows(5);
        aboutus_text.setText("Welcome to our cutting-edge laundromat app!\nSimplifying laundry chores, our user-friendly interface \nallows for easy scheduling and real-time machine tracking.\nSay farewell to wait times and hello to efficiency.\nExperience laundry made simple with us.");
        jScrollPane1.setViewportView(aboutus_text);

        contactus_text.setEditable(false);
        contactus_text.setColumns(20);
        contactus_text.setRows(5);
        contactus_text.setText("Email: autolaund@aus.edu\nPhone: 06-6666666");
        jScrollPane2.setViewportView(contactus_text);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/project/laundry.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(welcome_lbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aboutus_lbl)
                            .addComponent(contactus_lbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laund_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(516, 516, 516))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(laund_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcome_lbl)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(aboutus_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(contactus_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        machine_id_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        machine_id_lbl.setText("Machine ID:");

        consumption_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consumption_lbl.setText("Consumption:");

        loc_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loc_lbl.setText("Location:");

        consumption_field.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consumption_field.setText("-");

        loc_field.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loc_field.setText("-");

        status_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status_lbl.setText("Status(ON/OFF)");

        status_field.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status_field.setText("-");

        locked_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        locked_lbl.setText("Locked");

        locked_field.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        locked_field.setText("-");

        machineType_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        machineType_lbl.setText("Machine Type:");

        machineinfo_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        machineinfo_lbl.setText("Machine Information:");

        machineID_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        machineType_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Washer", "Dryer" }));

        search_btn.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(machine_id_lbl)
                    .addComponent(consumption_lbl)
                    .addComponent(loc_lbl)
                    .addComponent(status_lbl)
                    .addComponent(locked_lbl)
                    .addComponent(machineType_lbl))
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locked_field)
                    .addComponent(status_field)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(loc_field)
                        .addGap(190, 190, 190)
                        .addComponent(search_btn))
                    .addComponent(consumption_field)
                    .addComponent(machineID_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(machineType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(machineinfo_lbl)
                .addGap(378, 378, 378))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {consumption_lbl, loc_lbl, machine_id_lbl});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(machineinfo_lbl)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machine_id_lbl)
                    .addComponent(machineID_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machineType_lbl)
                    .addComponent(machineType_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status_lbl)
                    .addComponent(status_field))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locked_lbl)
                    .addComponent(locked_field))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumption_lbl)
                    .addComponent(consumption_field))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_lbl)
                    .addComponent(loc_field)
                    .addComponent(search_btn))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        feedback_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        feedback_lbl.setText("Your Feedback is Important!");

        submit_btn.setText("Submit");

        jButton1.setText("View All Feedback");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(149, 149, 149))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(feedback_lbl))
                    .addComponent(feedback_field, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(submit_btn)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(feedback_lbl)
                .addGap(43, 43, 43)
                .addComponent(feedback_field, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(submit_btn)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(96, 96, 96))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        bookmach_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookmach_lbl.setText("Book Machine");

        machineid_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        machineid_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machineid_comboboxActionPerformed(evt);
            }
        });

        machine_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        machine_lbl.setText("Machine ID:");

        avalibility_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        avalibility_lbl.setText("Avalability");

        aval_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aval_lbl.setText("Yes");

        bookmach_btn.setText("Book");
        bookmach_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmach_btnActionPerformed(evt);
            }
        });

        timeslot_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timeslot_lbl.setText("Time Slot");

        timeslot_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00AM", "9:00AM", "10:00AM", "11:00AM", "12:00PM", "1:00PM", "2:00PM", "3:00PM" }));
        timeslot_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeslot_comboboxActionPerformed(evt);
            }
        });

        price_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        price_lbl.setText("Price");

        price_field.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        price_field.setText("-");

        machine_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        machine_lbl1.setText("Machine Type:");

        machinetype_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Washer", "Dryer" }));
        machinetype_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machinetype_comboboxActionPerformed(evt);
            }
        });

        avalibility_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        avalibility_lbl1.setText("Cycles/Duration:");

        period_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        period_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                period_comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(machine_lbl1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bookmach_btn)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avalibility_lbl)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(aval_lbl))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeslot_lbl)
                                    .addComponent(price_lbl))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(timeslot_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(185, 185, 185)
                                        .addComponent(price_field))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(machine_lbl)
                            .addComponent(avalibility_lbl1))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(period_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(machineid_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(machinetype_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(bookmach_lbl)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(bookmach_lbl)
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machine_lbl1)
                    .addComponent(machinetype_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(machine_lbl)
                    .addComponent(machineid_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avalibility_lbl1)
                    .addComponent(period_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeslot_lbl)
                    .addComponent(timeslot_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_lbl)
                    .addComponent(price_field))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avalibility_lbl)
                    .addComponent(aval_lbl))
                .addGap(61, 61, 61)
                .addComponent(bookmach_btn)
                .addGap(78, 78, 78))
        );

        jTabbedPane1.addTab("tab4", jPanel5);

        offers_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        offers_lbl.setText("Offers:");

        coupon_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        coupon_lbl.setText("20% Coupon:");

        insta_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        insta_lbl.setText("Follow us on Insta for the deal of the week at: @LaundryAuto");

        coup_hash.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        coup_hash.setText("#BestProject");

        thirdbook_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        thirdbook_lbl.setText("Every third booked machine grants you an additional 15% off on the next!");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thirdbook_lbl)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(coupon_lbl)
                        .addGap(41, 41, 41)
                        .addComponent(coup_hash))
                    .addComponent(insta_lbl)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(offers_lbl)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(offers_lbl)
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coupon_lbl)
                    .addComponent(coup_hash))
                .addGap(30, 30, 30)
                .addComponent(insta_lbl)
                .addGap(40, 40, 40)
                .addComponent(thirdbook_lbl)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel6);

        myacc_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myacc_lbl.setText("My Account:");

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_lbl.setText("Email:");

        username_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username_lbl.setText("Username:");

        usertype_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usertype_lbl.setText("User Type:");

        phnum_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phnum_lbl.setText("Phone Num:");

        balance_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        balance_lbl.setText("Balance:");

        points_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        points_lbl1.setText("Points:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(myacc_lbl))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_lbl)
                            .addComponent(email_lbl)
                            .addComponent(usertype_lbl)
                            .addComponent(phnum_lbl)
                            .addComponent(balance_lbl)
                            .addComponent(points_lbl1))))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(myacc_lbl)
                .addGap(29, 29, 29)
                .addComponent(username_lbl)
                .addGap(27, 27, 27)
                .addComponent(email_lbl)
                .addGap(25, 25, 25)
                .addComponent(phnum_lbl)
                .addGap(29, 29, 29)
                .addComponent(usertype_lbl)
                .addGap(25, 25, 25)
                .addComponent(points_lbl1)
                .addGap(18, 18, 18)
                .addComponent(balance_lbl)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", jPanel7);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FAQ:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(466, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(453, 453, 453))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab7", jPanel8);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 960, 570));

        myAcc_menuBar.setText("My Account");

        view_acc_menuItem.setText("View Account");
        view_acc_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_acc_menuItemActionPerformed(evt);
            }
        });
        myAcc_menuBar.add(view_acc_menuItem);
        myAcc_menuBar.add(jSeparator2);

        logout_menuItem.setText("Log Out");
        logout_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuItemActionPerformed(evt);
            }
        });
        myAcc_menuBar.add(logout_menuItem);

        jMenuBar1.add(myAcc_menuBar);

        services_menuBar.setText("Services");

        homepage_menuItem.setText("Home Page");
        homepage_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_menuItemActionPerformed(evt);
            }
        });
        services_menuBar.add(homepage_menuItem);

        faq_menuitem.setText("FAQ");
        faq_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faq_menuitemActionPerformed(evt);
            }
        });
        services_menuBar.add(faq_menuitem);
        services_menuBar.add(jSeparator1);

        place_orderMenuItem.setText("Place Order");
        place_orderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_orderMenuItemActionPerformed(evt);
            }
        });
        services_menuBar.add(place_orderMenuItem);

        mach_info_menuItem.setText("Machine Information");
        mach_info_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mach_info_menuItemActionPerformed(evt);
            }
        });
        services_menuBar.add(mach_info_menuItem);

        prov_feedback_menuItem.setText("Provide Feedback");
        prov_feedback_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prov_feedback_menuItemActionPerformed(evt);
            }
        });
        services_menuBar.add(prov_feedback_menuItem);

        viewOffers_menuItem.setText("View Offers");
        viewOffers_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOffers_menuItemActionPerformed(evt);
            }
        });
        services_menuBar.add(viewOffers_menuItem);

        jMenuBar1.add(services_menuBar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void machineid_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machineid_comboboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_machineid_comboboxActionPerformed

    private void timeslot_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeslot_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeslot_comboboxActionPerformed

    private void bookmach_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmach_btnActionPerformed
        // TODO add your handling code here:
        new Payment_Gateway().setVisible(true);
    }//GEN-LAST:event_bookmach_btnActionPerformed

    private void place_orderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place_orderMenuItemActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_place_orderMenuItemActionPerformed

    private void mach_info_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mach_info_menuItemActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_mach_info_menuItemActionPerformed

    private void prov_feedback_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prov_feedback_menuItemActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_prov_feedback_menuItemActionPerformed

    private void viewOffers_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOffers_menuItemActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_viewOffers_menuItemActionPerformed

    private void logout_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuItemActionPerformed
        // TODO add your handling code here:
        (new LoginForm()).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_logout_menuItemActionPerformed

    private void homepage_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_menuItemActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_homepage_menuItemActionPerformed

    private void machinetype_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machinetype_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machinetype_comboboxActionPerformed

    private void view_acc_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_acc_menuItemActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_view_acc_menuItemActionPerformed

    private void faq_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faq_menuitemActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_faq_menuitemActionPerformed

    private void period_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_period_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_period_comboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Interface().setSize(897,576); // idk how to hide the right side of the tabbed pane
                new User_Interface().setVisible(true);
                
            }
        });
    }
    
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutus_lbl;
    private javax.swing.JTextArea aboutus_text;
    private javax.swing.JLabel aval_lbl;
    private javax.swing.JLabel avalibility_lbl;
    private javax.swing.JLabel avalibility_lbl1;
    private javax.swing.JLabel balance_lbl;
    private javax.swing.JButton bookmach_btn;
    private javax.swing.JLabel bookmach_lbl;
    private javax.swing.JLabel consumption_field;
    private javax.swing.JLabel consumption_lbl;
    private javax.swing.JLabel contactus_lbl;
    private javax.swing.JTextArea contactus_text;
    private javax.swing.JLabel coup_hash;
    private javax.swing.JLabel coupon_lbl;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JMenuItem faq_menuitem;
    private javax.swing.JTextField feedback_field;
    private javax.swing.JLabel feedback_lbl;
    private javax.swing.JMenuItem homepage_menuItem;
    private javax.swing.JLabel insta_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel laund_pic;
    private javax.swing.JLabel loc_field;
    private javax.swing.JLabel loc_lbl;
    private javax.swing.JLabel locked_field;
    private javax.swing.JLabel locked_lbl;
    private javax.swing.JMenuItem logout_menuItem;
    private javax.swing.JMenuItem mach_info_menuItem;
    private javax.swing.JComboBox<String> machineID_combobox;
    private javax.swing.JComboBox<String> machineType_combobox;
    private javax.swing.JLabel machineType_lbl;
    private javax.swing.JLabel machine_id_lbl;
    private javax.swing.JLabel machine_lbl;
    private javax.swing.JLabel machine_lbl1;
    private javax.swing.JComboBox<String> machineid_combobox;
    private javax.swing.JLabel machineinfo_lbl;
    private javax.swing.JComboBox<String> machinetype_combobox;
    private javax.swing.JMenu myAcc_menuBar;
    private javax.swing.JLabel myacc_lbl;
    private javax.swing.JLabel offers_lbl;
    private javax.swing.JComboBox<String> period_combobox;
    private javax.swing.JLabel phnum_lbl;
    private javax.swing.JMenuItem place_orderMenuItem;
    private javax.swing.JLabel points_lbl1;
    private javax.swing.JLabel price_field;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JMenuItem prov_feedback_menuItem;
    private javax.swing.JButton search_btn;
    private javax.swing.JMenu services_menuBar;
    private javax.swing.JLabel status_field;
    private javax.swing.JLabel status_lbl;
    private javax.swing.JButton submit_btn;
    private javax.swing.JLabel thirdbook_lbl;
    private javax.swing.JComboBox<String> timeslot_combobox;
    private javax.swing.JLabel timeslot_lbl;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JLabel usertype_lbl;
    private javax.swing.JMenuItem viewOffers_menuItem;
    private javax.swing.JMenuItem view_acc_menuItem;
    private javax.swing.JLabel welcome_lbl;
    // End of variables declaration//GEN-END:variables
}
